### ISSUE TITLE
how to "Open app" for a newly created repo?

### ISSUE THREAD

**Issue by mukil** [digitalmemex/repository-manager#5]
I created a "Repository" from scratch, placed my source code in the folder but now I don't know how to start/open the app. 

I tried to access `/app/my-folder-name` but that did not deliver my index.html.

Help is appreciated.

**Comment by carolinagc** [comment]
Hi,
When you create the "Repository" you are supposed to fill the git repo url field, then in the repository manager you click on "Install" and it should automatically clone the repository, and activate the "Open app" button (if not try to refresh the page) and then it will open the app.
In your file system you will find your app inside deepamehta-files/dmx
Hope it helps, if not ask again :-)

**Comment by mukil** [comment]
Thank you very much but this won't help, because "from scratch" means > please read issue #4.

**Comment by mukil** [comment]
Isn't there a way to "manually" open up my app, e.g. through entering the right URL/path into the address bar of my browser?

**Comment by mukil** [comment]
I found a way :)
Repository Status must be "Installed".
If one draws an "Aggregation" from the "Repository" to the existing topic "Installed" (of type "Repository Status") while the former is the "Parent" and the lattter is the "Child". The "Open app" button appears and works within the repository-manager.

**Comment by mukil** [comment]
duplicate, issues need to be solved in the backend, reported bug at https://github.com/digitalmemex/bootstrap/issues/2
